# Generated by Django 5.0.2 on 2024-02-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_menu_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='active',
            new_name='is_active',
        ),
    ]
